### ISSUE TITLE
Meta: Aquarium Improvement Tracking

### ISSUE THREAD

**Issue by bjjones** [JiangYizhou/aquarium-test#10]
This is a meta issue to track progress for Aquarium improvements, When complete, the workload will be better suited to show backend optimizations.

Items to be completed (in no specific order):

- [x] **#3 Remove FishPers hardcoded values**
- [ ] **#4 Optimize Mipmap Generation**
- [x] ~~**#5 Share lightFactorUniforms Between Like Models**~~
- [x] **#6 Share viewUniforms Globally**
- [x] **#7 Eliminate Redundant FishVertexUniforms Updates**
- [x] **#8 Eliminate Unnecessary DrawIndexed Calls**
- [x] **#9 Implement Individual Draws Option**
- [x] **#11 Add MSAA Functionality**

[Aquarium Workload Analysis.pdf](https://github.com/JiangYizhou/aquarium-test/files/3048867/Aquarium.Workload.Analysis.pdf)

**Comment by bjjones** [comment]
@JiangYizhou thanks for you efforts so far. I've taken a quick look at the before and after profiles of the workload and there's been a dramatic change. 

Frame time has been reduced 56%

Frame setup (mostly copies) used to be 54% of the frame, and now it accounts for ~2%,

Great work!

**Comment by JiangYizhou** [comment]
No problem. Thanks for your help and suggestions.
